### ISSUE TITLE
Lighthouse 6 ignores Angular Universal content until very TTI

### ISSUE THREAD

**Issue by h3d0** [GoogleChrome/lighthouse#10845]
#### Provide the steps to reproduce

1. Use example from https://angular.io/guide/universal

2. Run Lighthouse on the compiled Universal-powered app.
  
#### What is the current behavior?

LCP is reported at the very end (3s mark in my case):

![image](https://user-images.githubusercontent.com/7346327/82938055-e2141100-9f99-11ea-86d9-8bd1b4d815de.png)

Angular Universal renders the full page server-side and returns it to the browser pretty much on FP. After FP the content stays the same (isn't this considered Largest Contentful Paint when all content HTML is rendered?), yet Lighhouse wait until the very TTI (when all hydration and JavaScript is done).

![image](https://user-images.githubusercontent.com/7346327/82938954-3ff52880-9f9b-11ea-9020-933e264523cc.png)

#### What is the expected behavior?

LCP is counted correctly: content does not change = LCP is complete.

#### Environment Information
* Affected Channels: Node, DevTools -->
* Lighthouse version: 6.0.0
* Chrome version: 84
* Node.js version: 12.3.6
* Operating System: Linux Ubuntu 20.10

#### Comments

This change in the Lighthouse 6 automatically lowered the score from:

![image](https://user-images.githubusercontent.com/7346327/82939149-995d5780-9f9b-11ea-8a93-70a4a6b33028.png)

to:

![image](https://user-images.githubusercontent.com/7346327/82939187-a5491980-9f9b-11ea-9076-09b64c6bbd49.png)

And this is for a bare-bone example (with no code). How Angular Universal devs are supposed to ever match the new rules?

**Comment by h3d0** [comment]
Here is the similar issue I have found (related to FMP):
https://github.com/GoogleChrome/lighthouse/issues/4578

@patrickhulce :
> Looking at the performance monitor in DevTools for your page, the first paint where the page looks complete (beginning of timeline) is about ~600 elements, the hydration step shoots this up to ~2000 elements peaking at ~2400 before settling back down at around ~1200. This shoot up to 2000 is what gets labelled as "first meaningful paint" even though the initial 600 looked nearly identical.

Any ideas if it is possible to escalate this issue somehow to Lighhouse or Universal teams to get a feedback?

The issue would seem to affect every Universal-powered PWA - neglecting the efforts for a fast SEO-rich apps.

**Comment by patrickhulce** [comment]
Thanks for filing @h3d0! In this case, LCP is working as intended. The universal example app actually *removes* the largest elements from the DOM that were rendered server-side and renders new ones rather than simply wiring up listeners during hydration. 

Whether that's a bug in angular universal core or the way the example app is written I'm not sure.

**Example of the intermediate state while angular executes**
![image](https://user-images.githubusercontent.com/2301202/83054354-e979ff80-a017-11ea-8a7c-979358ddfb53.png)

Also worth noting that the v6 change feels so drastic because "Max Potential FID" was not previously scored in v5. It happens to be capturing the same issue that "Total Blocking Time" is in v6 but TBT actually has considerable weight. If it were just the LCP issue, things would not be so drastic.

**Comment by initplatform** [comment]
I am having the same issue.

Yes it does appear as though Angular Universal replaces the DOM, however why should that affect my page speed score if the user doesn't notice it?

I spent a lot of time setting up prerendering on my site. The initial html that comes down the pipe renders the entire page between 300- 400ms and then replaces the DOM once the app has loaded, which is at around a little over a second, sometimes close to 2. 

However, I have addressed all the content shift so there is none. And the user can still interact with the page. 

The user has no idea the content has been switched out. 

Is there any way to take into account the fact that the visuals do not change when determining LCP?

**Comment by h3d0** [comment]
@initplatform

There was quite a big discussion here - https://github.com/angular/angular/issues/13446. Angular team's lead **mgechev** seems to push the discussion to the Chromium team. 

Chromium team has created a ticket - https://bugs.chromium.org/p/chromium/issues/detail?id=1045640 and implemented an experimental feature which seems to count LCP correctly. 

Now Chrome 85 and 86 has been released, but they seem to not push the fix into the upstream. Either they don't have time for it, or they don't give a priority to it. Anyways, asking the teams, rising this question - may help to finally resolve the problem.

**Comment by initplatform** [comment]
Looks like there's some action now on https://bugs.chromium.org/p/chromium/issues/detail?id=1045640

Not sure if it's experimental support or full support, but one of them is going to land in Chrome 87

**Comment by sahilpurav** [comment]
I'm really hoping that this will fix soon. It impacts a large amount of organization who merely relies on the pagespeed.

**Comment by albanx** [comment]
I am still having this issue today, despite my application is fully server side rendered (and Interactive!!! for most of links working correctly), I get a bad TBT and Lighthouse score only because of Hydratation
![annotely_image](https://user-images.githubusercontent.com/1130664/169802552-158435b3-feaf-4eae-827f-d3c531c84c35.jpeg)
.

**Comment by bierzorutas** [comment]
Problem is still present, very annoying and very destructive for SEO purposes of all Angular Universal SSR users

**Comment by connorjclark** [comment]
You should open a new issue with repro steps. As it stands, the upstream chromium bug ticket suggest this has been resolved. Without a repro we can't investigate further.

**Comment by worthy7** [comment]
Hi I have spent many days and nights optimizing my app in in aid of improving my lighthouse score - yet it seems impossible to get any further. The remaining issues are down to angular actualy loading - the same as everyone else has said - and when it's finished it rerenders the DOM which lighthouse counts as the first real render. Very annoying, makes me not want to use angular for landing pages.
