### ISSUE TITLE
Lighthouse NO_LCP error

### ISSUE THREAD

**Issue by CDDelta** [GoogleChrome/lighthouse#10869]
Since Lighthouse was updated to include the LCP metric my site doesn't get a performance score anymore. The error text asks me to rerun Lighthouse but I have done so multiple times and there's no effect.

#### Provide the steps to reproduce
1. Run LH on https://cddelta.github.io/portfolio/
  
#### What is the current behavior?
Performance score is not calculated as no LCP could be measured.

#### What is the expected behavior?
LCP can be properly calculated or Lighthouse fails gracefully with a performance score when it cannot be.

#### Environment Information
Tested on web.dev and CI server running latest Lighthouse.

**Comment by akashdsouza** [comment]
[Related issue](https://github.com/GoogleChrome/lighthouse/issues/10499)

Try running on a latest version of chrome

**Comment by patrickhulce** [comment]
Thanks for filing @CDDelta! I can reproduce and this appears to be a bug in the LCP metric itself, we'll look into it 👍

**Comment by brunojcm** [comment]
In my case here I was having this problem just in CircleCI build, local one was working fine.

After updating the docker image from `circleci/node:12.7-browsers` to `circleci/node:12.18-browsers` CircleCI started to work fine as well, so the assumptions that this problem might be related to Chrome version seems to stand in my case.

**Comment by widmanski** [comment]
https://praesens.co also triggers the `NO_LCP` error. I first noticed the error in Lighthouse 6.0. I saw that there were a number of similar Issues reported here, so didn't report earlier. The website got a `100` before the 6.0 update. 

The error can be reproduced every time using any of the below (all return the `NO_LCP` error):
- web.dev
- Chrome 83.0.4103.116
- pagespeed insights
- lighthouse 6.x via node CLI 

Here is the JSON report from 6.1:
https://gist.github.com/widmanski/ea1357b99749a32c17910d2b802a28ed

Here is the JSON report from 5.6, when all metrics worked, and the score was 100:
https://gist.github.com/widmanski/3f68bca3a04fe43eef10a95b4397eac5

**Comment by patrickhulce** [comment]
Thanks @widmanski I can reproduce this as well!

**Comment by patrickhulce** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1104218 with these details 👍

**Comment by adamraine** [comment]
Looks like this has been fixed in chrome. Worth investigating to ensure LCP is reported on these sites.

**Comment by danielhaim1** [comment]
not for me @adamraine (v85.0.4183.121)

**Comment by RaicuRobert** [comment]
Same here

**Comment by hummal** [comment]
@patrickhulce in v85.0.4183.121 the bug is back. Do we have some regression here?
After some testing it seems to appear when the LCP happens to early (after 250ms) along with the FCP.
I can see in the screens that it shows the complete layouted page instantly. 

Maybe if there is no change in painting? Do the FCP calc need at least one change to be detected?

**Comment by patrickhulce** [comment]
@danielhaim1 @RaicuRobert @hummal thanks for the clarification! There are many types of pages that receive NO_LCP and this issue only tracks a very specific one (when the LCP element transitions from opacity 0 to a semi-opaque value).

If you're still receiving NO_LCP in Chrome Canary, **then this bug did not apply to you**. A separate issue with a reproducible case or public URL would be much appreciated :)

**Comment by patrickhulce** [comment]
Also @adamraine from our triage it looks like this is ["WAI" from the LCP spec perspective](https://bugs.chromium.org/p/chromium/issues/detail?id=1104218#c2) which is really unfortunate for us. We're at a dead end. 

I'll file an issue on the LCP spec repo.

**Comment by hummal** [comment]
@patrickhulce  Thank you Patrick for answering that quick. 

I can provide a live page for my tests: https://flug.check24.de/fluege/spanien
As we write I did another 3 tests in an incognito tab and the first 2 went through but the last one just did not finish due NO_LCP.
When it worked out the LCP was at 5.2s. Iam not in control of all the scripts that been loaded by this site. So especially the form is a blackbox for me. Iam pretty sure if there is an opacity animation then it is in there.

**Comment by patrickhulce** [comment]
Thanks for the extra info and the URL @hummal! There's something extra weird going on in Chromium for that URL I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1135165

I can also reproduce your intermittent behavior in Lighthouse. As part of the cookie loader, do you know if that *removes* any elements from the DOM when it loads?

**Comment by hummal** [comment]
Thanks for having a look into.

> As part of the cookie loader, do you know if that _removes_ any elements from the DOM when it loads?

As Iam checking the code I can only see that there is some height change:
`if (consentNotice.offsetHeight !== 0) {
                consentScreen.style.height = consentNotice.offsetHeight + "px"
            }`

Removed DOM elements are not in the code. 

Also I should mention that there are other products in this universe that do not have these problems. Such as: https://urlaub.check24.de/reisen/spanien
Those are using the same cookie loader. The only difference is the content and searchform below. All other code is under my control.

**Comment by widmanski** [comment]
The issue seems to persist for https://praesens.co - also tested in Lighthouse 6.4 @ Chrome 88

**Comment by patrickhulce** [comment]
Thanks @widmanski I can also reproduce on a minified version. I'll go back to bug the chromium issue that it's not fixed :)

**Comment by sebacampos** [comment]
> Thanks @widmanski I can also reproduce on a minified version. I'll go back to bug the chromium issue that it's not fixed :)
> 
> For future issue readers: there are two separate problems being discussed here:
> 
> * Element uses _transition_ to transition from opacity 0 to opacity 1 (crbug, discussed in https://bugs.chromium.org/p/chromium/issues/detail?id=1104218)
> * Element starts offscreen and moves onscreen (currently WAI, discussed in [WICG/largest-contentful-paint#61](https://github.com/WICG/largest-contentful-paint/issues/61))

Just wanted to let you know that your comment really helped me.
In my case,  the NO_LCP issue was caused by a CSS animation with **opacity** keyframes:

```
const HeroContainer = styled.div`
  width: 100vw;
  animation: fadein 2s;
  @keyframes fadein {
    0% {
      opacity: 0;
    }
    20% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
`

```

After removing the animation, Performance scoring started working normally again:
```
const HeroContainer = styled.div`
  width: 100vw;
`
```

**Comment by ClaryPollack** [comment]
I've just experienced this for the first time. @patrickhulce I read your reply from Oct. but, unfortunately, this bug is new for me so what worked in Oct. doesn't appear to work any longer :/

> Thanks @widmanski I can also reproduce on a minified version. I'll go back to bug the chromium issue that it's not fixed :)
> 
> For future issue readers: there are two separate problems being discussed here:
> 
> * Element uses _transition_ to transition from opacity 0 to opacity 1 (crbug, discussed in https://bugs.chromium.org/p/chromium/issues/detail?id=1104218)
> * Element starts offscreen and moves onscreen (currently WAI, discussed in [WICG/largest-contentful-paint#61](https://github.com/WICG/largest-contentful-paint/issues/61))

**Comment by connorjclark** [comment]
Hi @ClaryPollack, can you provide a URL so we can assist you?

**Comment by ClaryPollack** [comment]
@connorjclark wow, thank you for the fast reply. Was just about to let you all know that it resolved. Ironically, while the problematic element's didn't transition from opacity, I re-read @patrickhulce 's reply from Oct. and the issue was another transition. All is well now. Thank you both :)

**Comment by timlaughlin** [comment]
I am seeing this error for the first time as well both with the following URL and the dev tools version.

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsullivanbranding.com%2F&tab=desktop

**Comment by tonybatts** [comment]
Have been getting this same issue for months on this url 

https://www.tonybatts.com/

**Comment by tomhoad** [comment]
https://www.tomhoad.com, textbook case study of this issue

**Comment by haavardnk** [comment]
I have the same issue. It only happens when using [AOS](https://michalsnik.github.io/aos/) fade animations. Disabling them fixes the issue.
Also only happens when the page load is very quick, probably faster than the animation time. Slowing down load times with chrome extensions loaded does not give NO_LCP.

**Comment by TukuToi** [comment]
Same issue with a plain simple CSS animation.
The weird is that logged in the issue doesn't happen, logged out (which visitors will be) it does happen.

And a bit disappointing is that the tools which will determine a part of a site's score in future (see google's panic-making about favouring sites that are fast and score well), isn't even able to create a speed index for a simple CSS animation using some SVG elements moving over a screen.

This may or may not be a bug but it is certainly a tad annoying :)

**Comment by amaynez** [comment]
Hi all, read all the comments and tried all the suggestions to no avail, I am still getting the NO_LCP issue, but only for mobile on this site: https://the-mvm.github.io/ the desktop test passes perfectly with a high score.

**Comment by v-marinkov** [comment]
I just encountered the same problem. If I disable the animation-delay, LH passes in DevTools but it always fails at PageSpeed Insights. Are there any tricks for preserving the animation but still pleasing LH?

**Comment by Sharpshooter-Dublin** [comment]
> I have the same issue. It only happens when using [AOS](https://michalsnik.github.io/aos/) fade animations. Disabling them fixes the issue.
> Also only happens when the page load is very quick, probably faster than the animation time. Slowing down load times with chrome extensions loaded does not give NO_LCP.

I'm using AOS on all pages of my site but only some are throwing up the NO_LCP error. After coming across this thread, I deleted AOS on one troublesome page and it's now working perfectly. However, I've tried the same with other pages throwing up the error and it hasn't worked.

**Comment by DennysDionigi** [comment]
I got the same problem.
I moved many resources to github, and then used jsdeliver as CDN (https://www.jsdelivr.com/github)

What do y'all suggest I can do here: [https://whynot.media] (https://whynot.media )?

Values from Lighthouse are ok (except the Largest LPC which blocks the Performance Report) , while Gtmetrix and Web.Dev are literally killing me.

**Comment by xavierlxvii** [comment]
Same issue here. Using animations that go off screen and performance cannot be tested.

"Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)"

https://xavier.dev/

**Comment by gonssal** [comment]
Having the same issue with https://www.marinaportvell.com/, but only for the mobile section. Desktop always gives 99 and the animations are exactly the same.

After some testing, I've found that if I remove the transition-delay from the elements that appear later in the video hero and most of the other pages' big header sections, then I always get an score on mobile too. Of course I can't do this because the animations were already client-approved.

Also, if you try enough times, you end up getting a score, both from Lighthouse in dev tools and the Page Speed online service:
![marinaportvell-page-speed-mobile](https://user-images.githubusercontent.com/1172272/127507251-be414476-5c5d-4677-866a-c973f8c2e7be.png)

If this is really what Google uses to rank sites' performance on mobile and thus their position on searches, well I don't think it's good enough sadly.

**Comment by ahmed-abderraham** [comment]
@connorjclark while it's clear this issue is being ignored, can you please clarify if Lighthouse scores are being used to rank sites in Google and if they are penalized when not getting a performance score due to not having a LCP rating?

**Comment by patrickhulce** [comment]
This issue with offscreen animations is not a Lighthouse issue. It is a problem with the definition of Largest Contentful Paint itself (refer to https://github.com/GoogleChrome/lighthouse/issues/10869#issuecomment-703993158). Folks are free to vent frustrations at Lighthouse contributors, but it won't move anything forward :)

**Comment by ahmed-abderraham** [comment]
@patrickhulce I'm not venting any frustrations, I'm just asking if the fact that a website is affected by this issue, and thus not getting a Performance score from Lighthouse, will affect its Google Rank.

Considering Google has more than 90% marketshare and have publicly stated that performance is a strong rank factor, specially on mobile, I think it's a very reasonable question from a web developer that might get clients asking why their websites don't rank higher.

Thanks for the thumbs-down anyways.

**Comment by TukuToi** [comment]
@patrickhulce what is your statement based on?
This issue isn’t just happening with off screen animations
It’s unrelated to it, if anything, because I wouldn’t know what a logged in versus logged out user would change to an offscreen animation.

Surely just because I log in to my website won’t make animation on screen
And my animations aren’t even offscreen.
They are well inside the screen, just hidden with a covering div

Yes this issue is being ignored.
That’s what it means when many complain about an issue and no one in the position to adjust or at least feedback on it reacts
It’s the definition of ignoring something.

Also people aren’t venting here
They are reporting a „I see this too“ issue
If that would happen in my projects I’d at least have the grandeur to make a statement as of why I won’t give a *** about it or what people can do about it when they use my tool which (even if it’s not „my“ fault) is broken or acts unexpectedly or In unsatisfactory manner.
That’s just the respectful thing to do.

like @ahmed-abderraham question.
It is totally justified and even if not due to lighthouse (I wish that where true) they could still soothe people concerns because after all we are not seeing this issue in our staircase or random walk outside the house. We see it in lighthouse.

**Comment by patrickhulce** [comment]
> @patrickhulce what is your statement based on?

The fact that this issue explicitly tracks the LCP failure for offscreen animations as mentioned in several previous comments. e.g. https://github.com/GoogleChrome/lighthouse/issues/10869#issuecomment-703678478

> Yes this issue is being ignored.
That’s what it means when many complain about an issue and no one in the position to adjust or at least feedback on it reacts
It’s the definition of ignoring something.

If you see the above history, this issue is not being ignored. We've filed numerous Chromium and WICG bugs where the problem lies and periodically ping the respective owners for updates. If this issue is important to you, I recommend staring and upvoting *those issues* as the most productive path forward. What further action are you expecting *here*?

>  if Lighthouse scores are being used to rank sites in Google and if they are penalized when not getting a performance score due to not having a LCP rating

This core ranking question is never acknowledged here because this community does not have any additional information about search signals. You might be interested in [public comments made by search](https://twitter.com/JohnMu/status/1430988540763049992) in this area, but that does not answer your question on how  lack of LCP data affects ranking simply because **contributors here do not know the answer**.

**Comment by Wayne42** [comment]
Is this fixed yet?

**Comment by adamraine** [comment]
*Update*: This should be fixed for many sites with the latest stable Chrome (M97).

From my testing, the following sites don't experiencing this error anymore:
- https://xavier.dev/
- https://whynot.media/
- https://www.marinaportvell.com/
- https://www.tonybatts.com/
- https://www.tomhoad.com/
- https://praesens.co/#intro
- https://flug.check24.de/fluege/spanien

The following sites still produce the error:
- https://the-mvm.github.io/

Since this is still reproducible on some sites, I'm going to leave this open and continue tracking the upstream issue.

**Comment by tonybatts** [comment]
@adamraine Issue is fixed for my site!

Small note - Lighthouse used to show fireworks for 100% perfect score including PWA. 
<img width="604" alt="100" src="https://user-images.githubusercontent.com/44176115/151452635-54402b1c-c8e1-4510-86b6-48ae5b78c764.PNG">

Now it no longer does fireworks. 
<img width="535" alt="Screen Shot 2022-01-27 at 2 11 21 PM" src="https://user-images.githubusercontent.com/44176115/151452668-4cd4b244-2a56-4c09-98f8-bc5dba8285b5.png">

**Comment by adamraine** [comment]
That's over in https://github.com/GoogleChrome/lighthouse/issues/12563 if you're interested

**Comment by tonybatts** [comment]
Thanks! Also spoke too soon. The first lighthouse audit worked, but every subsequent audit as given me: Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)

**Comment by adamraine** [comment]
Ah yup, exact same thing happening to me on DevTools and the CLI.

**Comment by akd-io** [comment]
I am also getting this on my website, [akd.io](https://akd.io/).

**Comment by alexandrsek** [comment]
I am getting this error when profiling and auditing my Next.js app. In my case this happens when **body** tag has `margin:0;` 
But when I write `margin:1px;` for body selector lighthouse works just fine.

Version 99.0.4844.84 (Official Build) (x86_64)

**Comment by mwt** [comment]
I have this issue now both on the latest chrome and on pagespeed insights:
* https://mattwthomas.com/
I didn't have this error last month. Maybe it's a regression?

**Comment by abordage** [comment]
@mwt, you can solve this error by setting the animation's initial opacity to 0.01 
![image](https://user-images.githubusercontent.com/28537731/180834183-ad9263d1-62fb-4c1c-a956-06a8e8cfef7a.png)

**Comment by mwt** [comment]
> @mwt, you can solve this error by setting the animation's initial opacity to 0.01 
> ![image](https://user-images.githubusercontent.com/28537731/180834183-ad9263d1-62fb-4c1c-a956-06a8e8cfef7a.png)
> 

Thanks. That worked.

**Comment by tasesmuemils** [comment]
I have the same issue. 

https://preeminent-fudge-740573.netlify.app/

I have tried these options:
Set the opacity to 0.01 on first animation
Set hero logo div height to 99.5vh

Maybe someone can suggest something?

**Comment by adamraine** [comment]
@tasesmuemils From what I can tell, the only content elements visible are SVGs.

SVG elements do not qualify for LCP on their own: https://web.dev/lcp/#what-elements-are-considered

**Comment by Jiangmenghao** [comment]
> @mwt, you can solve this error by setting the animation's initial opacity to 0.01
> ![image](https://user-images.githubusercontent.com/28537731/180834183-ad9263d1-62fb-4c1c-a956-06a8e8cfef7a.png)

It works, Thank you very much!

**Comment by Coding-Kiwi** [comment]
For me the issue was that I have a 100vh x 100vw logo on the website and text only shows when you scroll down
as soon as I added a 
```
<span style="opacity: 0.01; user-select: none" class="this-is-for-google-ligthouse-lcp">Test</span>
```
Text to the dom (which sits in the top left corner) it works

This is really dumb.

**Comment by qorbani** [comment]
@Coding-Kiwi THIS IS CRAZY!!!!! After losing hours of debugging and trying to figure out what the ***** was going on with LCP, finally, I decided to do what you recommended, and WOWOWOWOWWO!!!! That fixed it!!! 

THIS IS SOOOOO DUMB, INDEED!!! 🤯

THANK YOU 🙏

**Comment by marijoo** [comment]
This problem occured today on [airline-strategy.com](https://airline-strategy.com) where some animations are done using `framer-motion`. Setting the initial `opacity` to `0.01` fixed the issue but I don’t like this fix.

**Comment by Quirksmode** [comment]
> @Coding-Kiwi THIS IS CRAZY!!!!! After losing hours of debugging and trying to figure out what the ***** was going on with LCP, finally, I decided to do what you recommended, and WOWOWOWOWWO!!!! That fixed it!!!
> 
> THIS IS SOOOOO DUMB, INDEED!!! 🤯
> 
> THANK YOU 🙏

Same issue for me, can't believe this was the fix, surprised this hasn't affected more people and therefore been fixed by now.

**Comment by philipp-winterle** [comment]
The problem is only with opacity: 0, which resolved if you set an opacity of 0.001. 

I would say placing an unused element in the top left corner is just shifting the problem and a proper missunderstanding of the reason why this happens. You should consider searching for your opacity settings in css and replace 0 with 0.001. Yes this is still not what we want and a wrong behavior how opacity is treated in lh but as long as this issue exists we have to live with it. 

Attention: An opacity of 0.01 is sometimes not enough. It can still be visible. To be sure to completely hide your element you have to use 0.001. Try out on the google.com main page and set opacity to 0.01 on the body element. You will see the google logo still shining through. 

I would suggest to use css variables to deal with the problem globally.  Use the variable everywhere you want to set opacity 0.

```css
:root {
  --opacity_0: 0.001;
}

.class-a {
  opacity: var(--opacity_0);
}
```
