### ISSUE TITLE
Move away from setBlockedUrls

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3516]
setBlockedUrls will be disappearing from the protocol and we should migrate to use request interception to do URL blocking instead

**Comment by benschwarz** [comment]
@patrickhulce request interception is (so far) only working with the `--headless` flag, but not without. Do you have any idea on when the fix for that will end up in stable?

**Comment by brendankenny** [comment]
will also help fix #2512

**Comment by patrickhulce** [comment]
@benschwarz my sources say that it's been fixed in canary, perhaps it'll go out with m63?

**Comment by benschwarz** [comment]
@patrickhulce I just tested [https://github.com/benschwarz/chrome-request-interception](chrome-request-interception) on Canary (latest) mac. 

* `--headless` wouldn't launch at all
* `Network.requestIntercepted` is never fired (on non-headless)

Definitely want to see this change come through, but it seems like request interception is still not ready

**Comment by patrickhulce** [comment]
the --headless problem seems to be based on the order of your listeners, due to PlzNavigate, you must establish all your handlers/listeners *before* `Page.navigate` since it can frequently resolve after the page has already loaded, moving around the listeners gets the example to work for me on headless.

non-headless definitely still seems to be missing interception though still perhaps my source jumped the gun 😄

**Comment by paulirish** [comment]
Good repro for broken setblockedURL: Try running lighthouse against http://2015.cssconf.com.au

**Comment by Hoten** [comment]
So, network interception is much better now, so we can probably do this now.

Also :)
https://github.com/GoogleChrome/lighthouse/blob/cc8e2d913c39bdf75c277afb7ca9e783d14b0413/lighthouse-core/gather/driver.js#L1560

**Comment by connorjclark** [comment]
If we still want to do this, we'll want to use the Fetch domain. This PR has the necessary code: https://github.com/GoogleChrome/lighthouse/pull/9459/files#diff-20c9b77b021305db443ebff30875575a

**Comment by connorjclark** [comment]
`Network.setBlockedURLs` never went away 🤷
