### ISSUE TITLE
PWA not applicable audits are misleading

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/lighthouse#5558]
#### Provide the steps to reproduce
1. Run LH on any webpage (for example on youtube.com).

#### What is the current behavior?
![screenshot_185](https://user-images.githubusercontent.com/31345346/41910616-7b6c7450-794a-11e8-82c3-d3e0e81adec7.png)

(console is count to that)

#### What is the expected behavior?
No error, viewport is correctly if set dock side of console at bottom or as external window.

#### Environment Information
* Affected Channels: 
*Chrome: 67.0.3396.99
a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}
* Operating System: Windows 10

V8 6.7.288.46
**Related issues**

**Comment by patrickhulce** [comment]
For others trying to reproduce, this requires that mobile emulation be disabled and you run in DevTools.

More broadly, I think this audit is 100% useless when mobile emulation is disabled anyhow since it's only catching cases where the content isn't sized the same as the viewport on a phone. Perhaps we should mark not applicable when mobile emulation is off?

**Comment by paulirish** [comment]
likely resolved with https://github.com/GoogleChrome/lighthouse/pull/5893

**Comment by exterkamp** [comment]
Have we confirmed this is fixed?

**Comment by Mlocik97-issues** [comment]
Chrome 72.0.3626.119 again that bug

**Comment by patrickhulce** [comment]
@Mlocik97-issues the fix for this is not in v3.2.0 which is what is currently in stable Chrome. The fix should be in the next major version of Chrome in Lighthouse v4.0.0-alpha and higher.

**Comment by patrickhulce** [comment]
So while it's true that Chrome 72.0.3626.119 never had the fix to begin with and is expected to fail, even in with versions of Lighthouse that have the fix, Chrome will still fail. 

The workaround in LH uses `emulatedFormFactor` but Chrome DevTools is still using the deprecated `disableDeviceEmulation` https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/audits2/Audits2Controller.js?type=cs&q=disableDeviceEmulation+-f:out+f:audits&sq=package:chromium&g=0&l=242

IMO, we should fix this Chrome-side.

**Comment by AubreyHewes** [comment]
The problem seems to be more than just an attached dev tools, it seems to also be applicable when the dev tools are detached.. (if this is already known ignore the following ;-))

(Chrome 73.0.3683.75)

Test via minimal html at https://wn2v4zmv58.codesandbox.io/
Open devtools, detach and then audit... 

e.g.
````lighthouse
The viewport size is 1454px, whereas window size is 1462px
The viewport size is 1981px, whereas window size is 1989px
````
The difference (when detached) is always 8px? could it in this case be the scrollbar?

The audit pass description of

> The audit passes if `window.innerWidth === window.outerWidth`.

Seems to not be the actual test/audit?

**Comment by jflayhart** [comment]
Still a bug for me docking PWA score when it's actually fine.

<img width="771" alt="Screen Shot 2019-09-17 at 10 23 21 AM" src="https://user-images.githubusercontent.com/6808172/65055852-89ce3f00-d935-11e9-8e1a-0e02983f16bb.png">
<img width="358" alt="Screen Shot 2019-09-17 at 10 23 50 AM" src="https://user-images.githubusercontent.com/6808172/65055880-92bf1080-d935-11e9-81aa-fb90fa9ab2f7.png">

**Comment by connorjclark** [comment]
@jflayhart please provide a URL. I only see a grey circle for that audit in 77 (which is wrong too ...)

@paulirish the `isMobile always false` bug is in 77 ([doc you made for reference](https://docs.google.com/document/d/1MV4mSMwZt8nrABagemK134PgJ66KToFjKq6Kg7WzyyE/edit?ts=5d51bee8)). Which I suppose is better than always failing, since the multi-client CL didn't make it to 77 either.

**Comment by Mlocik97-issues** [comment]
seems it's fixed in Chrome 77.

**Comment by connorjclark** [comment]
Update - there is a bug in 77 where the content-width (and thus PWA) will always fail. If there is another stable release for 77, then there will be an update that disabled this audit. For 78+, the root cause was fixed and the PWA category will work fully as expected.

**Comment by AndrewBogdanovTSS** [comment]
It's still reproducible for me in Chrome 77, although I can't reproduce it with latest Canary 79 so let's hope it's already resolved and will land to stable soon

**Comment by Mlocik97-issues** [comment]
no mne to dáva u desktop emulácie "scoreDisplayMode": "notApplicable", čož myslím že je správne. LightHouse 5.2.0 v Chrome 77.0.3865.90

**Comment by davidwieler** [comment]
This is still an issue in Version 78.0.3904.108

running `window.innerWidth === window.outerWidth` when dev tools is docked to the side results in false. As an external window or docked to bottom, it returns true but "Content is sized correctly for the viewport" still fails.

Although, it is grey so I'd assume it's not actually counting towards the PWA score..?

**Comment by patrickhulce** [comment]
>  it is grey so I'd assume it's not actually counting towards the PWA score

If it is grey it is not applicable and not affecting your score. Is there a reason you say you're seeing it as an issue @davidwieler?

I'm not able to reproduce any behavior other than notApplicable when run as desktop in Canary 81.0.4041.3, the original root issue here.

**Comment by ConradSollitt** [comment]
Found this happening the latest Chrome Build (tested on macOS):
* Version 87.0.4280.88 (Official Build) (x86_64)

**Result:**
* No Error when selecting `Mobile` for the device type
* Gray dot with warning (but no details) when selecting `Desktop` for the device type. Happens if either DevTools are docked or not.
* Doesn't affect the score though but the gray dot and warning did make me stop and double check my app so I would expect the same for other developers who go through every item.

Not sure if this is related but when docked `innerWidth` equals `document.documentElement.scrollWidth` instead of `outerWidth`:
```js
(window.innerWidth === document.documentElement.scrollWidth) === true
(window.innerWidth === window.outerWidth) === false
```

However the Lighthouse source is using a different API:
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/content-width.js

**Comment by patrickhulce** [comment]
> Gray dot with warning (but no details) when selecting Desktop for the device type. Happens if either DevTools are docked or not.

@ConradSollitt what warning are you seeing? A gray dot means the audit doesn't apply to the situation, it shouldn't have details when this happens.

**Comment by ConradSollitt** [comment]
@patrickhulce 

Here is a screenshot:

![image](https://user-images.githubusercontent.com/57777521/102752399-5fc8b100-431e-11eb-8158-aed955f472ef.png)

The app is a private app I wrote but if you wanted to investigate further I could recreate a basic demo if needed. Here is a quick overview of part of the code that might cause the issue (just speculating/guessing though). The layout works in all tested browsers; basically 100% viewport height and width and  a top nav allows for scrolling and panning as it is much wider than the page.

**HTML from the page:**
```html
<body>
   <nav>
     <div></div>
  </nav>
</body>
```

**CSS from the page:**
```css
body, html {
    height: 100vh;
    width: 100vw;
}

nav {
    position: absolute;
    overflow-x: scroll;
    top: 0;
    left: 0;
    right: 0;
    touch-action: pan-x;
    z-index: 10;
}

nav div {
    display: flex;
    width: fit-content;
    margin-left: 20px;
}
```

**Comment by patrickhulce** [comment]
Ah @ConradSollitt that's not a warning, that's the audit saying the "Content is sized correctly for the viewport", the audit's advice is not applicable, and everything is working as expected in Lighthouse.

Is there anything in particular that would've helped clarify this? Warnings in the report are big yellow bold text blocks while not applicable audits are gray.

**Comment by ConradSollitt** [comment]
Ah, I see now, thanks @patrickhulce 

Two ideas come to my mind initially that could help clarify this (mockups below):

## Option 1
A summary legend below PWA title and description and above the audits. This would require the most effort however from UX standpoint I think it would be helpful; and for the UI adding a simple legend look nice and visually flows with the rest of the UI in my opinion.
![image](https://user-images.githubusercontent.com/57777521/102818994-87a02f00-4387-11eb-8576-6f51c0f466b3.png)

When clicking back to Best Practices I see something similar but when I was focused on PWA updates I didn't notice the Best Practices legend it was already at 100 so I didn't check it for the particular app.
![image](https://user-images.githubusercontent.com/57777521/102819051-a0104980-4387-11eb-9f79-fa22edc8cec5.png)

## Option 2
If this is the only item skipped on desktop then perhaps a brief info message next to the item.
![image](https://user-images.githubusercontent.com/57777521/102819461-583df200-4388-11eb-9d7e-50b396176553.png)

In this for a Non-PWA, I see helpful info messages next to the audit failures but not for the skipped item.
![image](https://user-images.githubusercontent.com/57777521/102819215-eebde380-4387-11eb-9027-7aa4dcbd72f3.png)

## Original Bug Fixed
Additionally, I would consider the original bug topic to be fixed so this issue could be closed out unless it makes sense to keep open. I've tested on both Mac and Windows now using Chrome 87 and it works for Mobile when DevTools is either docked or opened in a separate window:

![image](https://user-images.githubusercontent.com/57777521/102819300-144aed00-4388-11eb-9c1f-dd94beeddb7b.png)

**Comment by patrickhulce** [comment]
Thanks for suggestions @ConradSollitt we'll leave this open and let it track better UX around this issue since several people have been tripped up by it here.

**Comment by ConradSollitt** [comment]
Thanks for your help @patrickhulce and great work on Lighthouse! I've used it a lot to help improve the speed of sites I work on and learn about new performance issues that I might not come across without it.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
