### ISSUE TITLE
Moonlight and Chrome extension are reporting different values for page load performance

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/lighthouse#577]
Ran against https://events.google.com/io2016/

The two are different enough to make me think one isn't right.

Extension:
![image](https://cloud.githubusercontent.com/assets/8204171/17562520/16d6eaa6-5ee0-11e6-954f-98c51873fccb.png)

Moonlight:
![image](https://cloud.githubusercontent.com/assets/8204171/17562531/27bea0a2-5ee0-11e6-8121-34e3ddd017d8.png)

**Comment by brendankenny** [comment]
Need to verify, but I believe this will just be fixed by moonlight updating to master, which will add the trace fix in #561

**Comment by brendankenny** [comment]
@crhym3

**Comment by crhym3** [comment]
good point, I'll sync with lighthouse master.
note that moonlight's using headless_shell exclusively. could that also contribute to the difference?

**Comment by crhym3** [comment]
Sorry it took me so long. Updated moonlight to use the latest lighthouse (https://github.com/GoogleChrome/lighthouse/commit/3f3e5c24462e77cde3f75d0d5669083df76fbcc4) and synched with headless_shell which now also includes libmesa (GPU) among other things.

Still seeing different results:

![screenshot from 2016-08-17 10 44 50](https://cloud.githubusercontent.com/assets/25405/17730274/4ff744c4-6468-11e6-8a47-87d253ef3a8c.png)

How are Speed Index and Time To Interactive are calculated? (sorry, I'm too lazy)

**Comment by paulirish** [comment]
Screenshots are not being recorded in the trace in the case of headless.
We'll need help to fix that. Hmm.

**Comment by paulirish** [comment]
Here's our chromium ticket for screenshots + headless: https://bugs.chromium.org/p/chromium/issues/detail?id=627547

**Comment by paulirish** [comment]
The downstream issue is fixed. We need to bump the devtools-frontend-package to something >= 421708
