### ISSUE TITLE
Cannot read property '_destroySSL' of undefined at destroySSL

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#73]
Just tried running a lighthouse trace and hit the following issues:
- launch-chrome.sh is OS X. Would it be worth considering moving this to an npm script and using [which](https://www.npmjs.com/package/which) to pick the version of chrome to use
- Node 5.9.1 is required. We could add a check for >= 5.9 and throw a warning otherwise
- On linux I get the following error:

    TypeError: Cannot read property '_destroySSL' of undefined
    at destroySSL (_tls_wrap.js:370:7)

Going to dig into that one and try and figure out the problem but wanted to raise an issue on it..

**Comment by gauntface** [comment]
Looks like:

    TypeError: Cannot read property '_destroySSL' of undefined
    at destroySSL (_tls_wrap.js:370:7)

is coming from the chrome remote interface `close()` call. Not sure there is anything that can be done to silence the error

**Comment by paulirish** [comment]
I tried to diagnose this exception but only got so far. I'm pretty sure it's a node core bug, as that area has gotten some fixes.

**Comment by paulirish** [comment]
> TypeError: Cannot read property '_destroySSL' of undefined at destroySSL (_tls_wrap.js:370:7)

Took another stab last night. AFAIK, this is due to the `request` call for the manifest, and not cri's `close()`. :relieved:  So we'll be done with it soon.

**Comment by paulirish** [comment]
Broke out the other two issues into #106 and #105. 

Retitled this to be just the destroySSL. This will be fixed when #83 is done. \o/

**Comment by paulirish** [comment]
fixed by #83

**Comment by paulirish** [comment]
Just ran into this problem again, while working on `pwmetrics`.. here's what I found out:

the _destroySSL stuff is happening inside _tls_wrap, which the `request` module uses:
![image](https://cloud.githubusercontent.com/assets/39191/21671005/64045bf4-d2cd-11e6-8a01-0e811d2537b3.png)

As you can see, the `this` is passed as a parameter to `setImmediate` but a heartbeat later, that param isn't there. And why not?

`chrome-devtools-frontend` has been polyfilling setImmediate, and unfortunately for us... incorrectly: 
![image](https://cloud.githubusercontent.com/assets/39191/21671031/8c57cc1c-d2cd-11e6-85d0-9cbae2461825.png)

:)

**Comment by ebidel** [comment]
I just ran into this using lighthouse 1.4.1 as a submodule. @paulirish did you ever submit a CL for devtools?

**Comment by paulirish** [comment]
Yes. Fixed over there: https://codereview.chromium.org/2615083002

But we'll need to bump our dependency to handle the update: https://github.com/GoogleChrome/lighthouse/issues/1535

**Comment by mohsen1** [comment]
Still seeing this in TravisCI when I launch chrome programmatically

**Comment by two7sclash** [comment]
still seeing this too, running lighthouse on heroku.

**Comment by paulirish** [comment]
@two7sclash evaluate this after lighthouse is required:

```js
 self.setImmediate = function(callback, ...argsForCallback) {
    Promise.resolve().then(() => callback(...argsForCallback));
    return 0;
  };
```

sorry for this, guys.
